import {
  SiJavascript,
  SiPython,
  SiMarkdown,
  SiYaml,
  SiLatex,
  SiReact,
  SiNextdotjs,
  SiAstro,
  SiTailwindcss,
  SiGithub,
  SiLinkedin,
  SiInstagram,
  SiFigma,
  SiOpencv,
  SiNodedotjs,
  SiHono,
  SiTrpc,
  SiExpo,
  SiPrisma,
  SiDrizzle,
  SiSupabase,
  SiFirebase,
  SiTurborepo,
  SiHoppscotch,
  SiGithubactions,
  SiRoboflow,
  SiVercel,
  SiNetlify,
  SiRender,
  SiCloudflare,
  SiTwilio,
  SiArduino,
  SiRaspberrypi,
  SiTypescript,
  SiShadcnui,
  SiFramework,
  SiFramer,
  SiJekyll,
  SiPostgresql,
  SiJsonwebtokens,
} from "react-icons/si";
import { DiRedis } from "react-icons/di";
import { FaBrain, FaFileAlt, FaGlobe, FaLayerGroup, FaServer } from "react-icons/fa";
import { HiMiniCpuChip, HiMiniCommandLine } from "react-icons/hi2";

export const SITE_CONFIG = {
  title: "Alvin Dennis — Builder | Maker | Manager",
  author: "Alvin Dennis",
  description:
    "Builder, maker, and developer passionate about crafting digital solutions and innovative technology. I blend creativity with technical expertise to solve real-world problems and empower communities.",
  lang: "en",
  siteLogo: "/logo.png",
  socialLinks: [
    {
      text: "Resume",
      href: "https://resume.alvindennis.tech/",
      icon: FaFileAlt,
    },
    {
      text: "Github",
      href: "https://github.com/alvin-dennis/",
      icon: SiGithub,
    },
    {
      text: "LinkedIn",
      href: "https://www.linkedin.com/in/alvindennis/",
      icon: SiLinkedin,
    },
    {
      text: "Instagram",
      href: "https://www.instagram.com/_a.lvin._/",
      icon: SiInstagram,
    },
  ],
  socialImage: "/og.webp",
  canonicalURL: "https://alvindennis.tech",
  contact: {
    email: "alvindennis80@gmail.com",
    cal_link: "https://cal.com/alvindennis",
  },
};

export const SITE_CONTENT = {
  hero: {
    name: "Alvin Dennis",
    specialty: [
      "Electrical Engineer",
      "Frontend Developer",
      "UI/UX Designer",
      "IoT Enthusiast",
      "Manual Software Tester",
      "Bot Developer",
      "Freelancer",
      "Community Manager",
      "Open Source Enthusiast",
      "Innovator",
    ],
    summary: `
      Builder and Maker, combining technical skills with creative problem-solving to deliver impactful, user-focused solutions.
    `,
    currentWork: "Frontend Engineer at MetaLoom",
    location: "Kottayam, Kerala",
    image: "https://github.com/alvin-dennis.png",
  },
  skills: {
    languages: [
      { name: "JavaScript", icon: SiJavascript },
      { name: "Python", icon: SiPython },
      { name: "Markdown", icon: SiMarkdown },
      { name: "YAML", icon: SiYaml },
      { name: "LaTeX", icon: SiLatex },
    ],
    libraries: [
      { name: "React", icon: SiReact },
      { name: "Astro", icon: SiAstro },
      { name: "Tailwind CSS", icon: SiTailwindcss },
      { name: "OpenCV", icon: SiOpencv },
      { name: "Prisma", icon: SiPrisma },
      { name: "Drizzle", icon: SiDrizzle },
    ],
    frameworks: [
      { name: "Next.js", icon: SiNextdotjs },
      { name: "Jekyll", icon: SiJekyll },
      { name: "Node.js", icon: SiNodedotjs },
      { name: "Hono.js", icon: SiHono },
      { name: "oRPC", icon: SiTrpc },
      { name: "Expo", icon: SiExpo },
      { name: "Pathway", icon: SiFramework },
    ],
    databases: [
      { name: "Supabase", icon: SiSupabase },
      { name: "Firebase", icon: SiFirebase },
      { name: "Upstash Redis", icon: DiRedis },
      { name: "Postgresql", icon: SiPostgresql },
    ],
    tools: [
      { name: "Turborepo", icon: SiTurborepo },
      { name: "HoppScotch", icon: SiHoppscotch },
      { name: "Figma", icon: SiFigma },
      { name: "GitHub Actions", icon: SiGithubactions },
      { name: "RoboFlow", icon: SiRoboflow },
    ],
    hardware: [
      { name: "Arduino", icon: SiArduino },
      { name: "Raspberry Pi", icon: SiRaspberrypi },
    ],
    platforms: [
      { name: "Vercel", icon: SiVercel },
      { name: "Netlify", icon: SiNetlify },
      { name: "Render", icon: SiRender },
      { name: "Cloudflare", icon: SiCloudflare },
      { name: "Github", icon: SiGithub },
      { name: "Twilio", icon: SiTwilio },
    ],
  },
  experience: [
    {
      company: "MetaLoom",
      position: "Frontend Engineer",
      start: "Jul 2025",
      end: "Present",
      link: "https://metaloom.vercel.app/",
      logo: "https://github.com/MetaLoomLabs.png",
    },
    {
      company: "BuilderClan",
      position: "Technical Lead",
      start: "January 2025",
      end: "Present",
      link: "https://builderclan.org/",
      logo: "https://github.com/builderclan.png",
    },
    {
      company: "Tinkerhub",
      position: "Community Management Intern",
      start: "December 2024",
      end: "May 2025",
      link: "https://app.tinkerhub.org/",
      logo: "https://github.com/tinkerhub.png",
    },
    {
      company: "Radio Community SJCET",
      position: "Operations Lead",
      start: "September 2024",
      end: "March 2025",
      link: "https://radiocommunity.sjcetpalai.ac.in",
      logo: "https://github.com/Radio-Community-SJCET.png",
    },
    {
      company: "Gtech Mulearn SJCET",
      position: "Campus Co-Lead",
      start: "June 2024",
      end: "February 2025",
      link: "https://mulearn.sjcetpalai.ac.in",
      logo: "https://github.com/mulearn-sjc.png",
    },
    {
      company: "Startup Bootcamp SJCET-IEDC",
      position: "Chief Finance Officer",
      start: "September 2023",
      end: "March 2025",
      link: "https://iedc.sjcetpalai.ac.in/",
      logo: "https://github.com/IEDC-SJCET.png",
    },
    {
      company: "Radio Community SJCET",
      position: "Technical Lead",
      start: "November 2023",
      end: "August 2024",
      link: "https://radiocommunity.sjcetpalai.ac.in",
      logo: "https://github.com/Radio-Community-SJCET.png",
    },
    {
      company: "Gtech Mulearn",
      position: "QA IG Lead Intern",
      start: "October 2023",
      end: "March 2024",
      link: "https://app.mulearn.org",
      logo: "https://github.com/gtech-mulearn.png",
    },
    {
      company: "Startup Bootcamp SJCET-IEDC",
      position: "Technical Officer",
      start: "June 2022",
      end: "August 2023",
      link: "https://iedc.sjcetpalai.ac.in/",
      logo: "https://github.com/IEDC-SJCET.png",
    },
  ],
  education: [
    {
      name: "St. Josephs College of Engineering & Technology",
      location: "Palai, Kerala, India",
      position: "B.Tech in Electrical & Electronics Engineering",
      start: "November 2021",
      end: "July 2025",
      link: "https://sjcetpalai.ac.in/",
      logo: "https://sjcetpalai.ac.in/wp-content/uploads/2019/01/SJCET-LOGO-Orginal-1200x1161.png",
    },
  ],
  categories: [
    { value: "all", label: "All", icon: FaLayerGroup },
    { value: "frontend", label: "Frontend", icon: FaGlobe },
    { value: "backend", label: "Backend", icon: FaServer },
    { value: "tools", label: "Tools", icon: HiMiniCommandLine },
    { value: "genai", label: "GenAI", icon: FaBrain },
    { value: "hardware", label: "Hardware", icon: HiMiniCpuChip },
  ],
  projects: [
    {
      name: "µLearn Home",
      description:
        "µLearn is a synergic philosophy of education, with a culture of mutual learning through micro groups of peers.",
      category: ["Frontend"],
      url: "https://github.com/gtech-mulearn/mulearnhome",
      hosted_url: "https://mulearnhome.vercel.app/",
      technologies: [
        { name: "Next.js", icon: SiNextdotjs },
        { name: "Tailwind CSS", icon: SiTailwindcss },
        { name: "Framer Motion", icon: SiFramer },
        { name: "Shadcn/UI", icon: SiShadcnui },
      ],
    },
    {
      name: "Personal Portfolio",
      description:
        "Professional developer portfolio utilizing modern minimal layout with responsive design and accessibility features.",
      category: "Frontend",
      url: "https://github.com/alvin-dennis/alvin-dennis.github.io",
      hosted_url: "https://alvindennis.tech/",
      technologies: [
        { name: "Astro", icon: SiAstro },
        { name: "TypeScript", icon: SiTypescript },
        { name: "Tailwind CSS", icon: SiTailwindcss },
        { name: "Shadcn/UI", icon: SiShadcnui },
      ],
    },
    {
      name: "Beyond Syllabus",
      description:
        "Beyond Syllabus a platform that transforms any syllabus into an interactive AI-powered learning companion.",
      category: ["Frontend", "Backend", "GenAI"],
      url: "https://github.com/The-Purple-Movement/Beyond-Syllabus",
      hosted_url: "https://beyondsyllabus.in/",
      technologies: [
        { name: "Next.js", icon: SiNextdotjs },
        { name: "Tailwind CSS", icon: SiTailwindcss },
        { name: "Framer Motion", icon: SiFramer },
        { name: "Elysia", icon: SiNodedotjs },
      ],
    },
    {
      name: "BuilderClan Website",
      description:
        "BuilderClan is a tech community for innovators, developers, and enthusiasts to collaborate on impactful projects.",
      category: "Frontend",
      url: "https://github.com/BuilderClan/builderclan-site",
      hosted_url: "https://builderclan.org/",
      technologies: [
        { name: "Next.js", icon: SiNextdotjs },
        { name: "Tailwind CSS", icon: SiTailwindcss },
        { name: "Framer Motion", icon: SiFramer },
      ],
    },
    {
      name: "EleGuard",
      description:
        "Smart elephant monitoring system with real-time hazard detection and notification capabilities.",
      category: "Hardware",
      url: "https://github.com/alvin-dennis/EleGuard",
      hosted_url: "https://github.com/alvin-dennis/EleGuard",
      technologies: [
        { name: "Python", icon: SiPython },
        { name: "Raspberry Pi", icon: SiRaspberrypi },
        { name: "Roboflow", icon: SiRoboflow },
        { name: "OpenCV", icon: SiOpencv },
        { name: "Twilio", icon: SiTwilio },
      ],
    },
    {
      name: "Availr",
      description:
        "An interactive CLI streamlines availability scheduling through CSV import, personalized email invites, and confirmation tracking.",
      category: "Tools",
      url: "https://github.com/alvin-dennis/Availr",
      hosted_url: "https://github.com/alvin-dennis/Availr",
      technologies: [
        { name: "Nodejs", icon: SiNodedotjs },
        { name: "Hono", icon: SiHono },
        { name: "JWT", icon: SiJsonwebtokens },
      ],
    },
  ],
};
