import { DiRedis } from "react-icons/di";
import { FaBrain, FaFileAlt, FaGlobe, FaLayerGroup, FaServer } from "react-icons/fa";
import { FiMail } from "react-icons/fi";
import { HiMiniCpuChip } from "react-icons/hi2";
import {
  SiArduino,
  SiAstro,
  SiCloudflare,
  SiDrizzle,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGithub,
  SiGithubactions,
  SiHono,
  SiHoppscotch,
  SiInstagram,
  SiJavascript,
  SiLinkedin,
  SiMarkdown,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiOpencv,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiRaspberrypi,
  SiReact,
  SiReactquery,
  SiRender,
  SiRoboflow,
  SiShadcnui,
  SiSupabase,
  SiTailwindcss,
  SiTurborepo,
  SiTwilio,
  SiTypescript,
  SiVercel,
  SiVite,
  SiYaml,
} from "react-icons/si";

// Sanity documents can't store React component references, so icon fields are
// persisted as string keys and resolved back to components here on the client.
export const skillIconMap: Record<string, React.ElementType> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  markdown: SiMarkdown,
  yaml: SiYaml,
  react: SiReact,
  astro: SiAstro,
  tailwindcss: SiTailwindcss,
  drizzle: SiDrizzle,
  prisma: SiPrisma,
  reactquery: SiReactquery,
  nextdotjs: SiNextdotjs,
  nodedotjs: SiNodedotjs,
  hono: SiHono,
  supabase: SiSupabase,
  firebase: SiFirebase,
  redis: DiRedis,
  postgresql: SiPostgresql,
  vite: SiVite,
  turborepo: SiTurborepo,
  hoppscotch: SiHoppscotch,
  figma: SiFigma,
  githubactions: SiGithubactions,
  arduino: SiArduino,
  raspberrypi: SiRaspberrypi,
  vercel: SiVercel,
  netlify: SiNetlify,
  render: SiRender,
  cloudflare: SiCloudflare,
  github: SiGithub,
  twilio: SiTwilio,
  framer: SiFramer,
  shadcnui: SiShadcnui,
  roboflow: SiRoboflow,
  opencv: SiOpencv,
};

export const categoryIconMap: Record<string, React.ElementType> = {
  layergroup: FaLayerGroup,
  globe: FaGlobe,
  server: FaServer,
  brain: FaBrain,
  cpuchip: HiMiniCpuChip,
};

export const socialIconMap: Record<string, React.ElementType> = {
  resume: FaFileAlt,
  email: FiMail,
  github: SiGithub,
  linkedin: SiLinkedin,
  instagram: SiInstagram,
};
